name: Docs
on:
  push:
    branches:
      - main

jobs:
  kdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: "Build docs with Dokka"
        run: ./gradlew dokkaHtml

      - name: "Publish Dokka"
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          publish_dir: 'lib/build/docs'
